version: '3'
services:
  app:
    build:
      context: .
      args:
        VARIANT: 18-bullseye
    user: node
    volumes:
      - ~/.ssh:/home/node/.ssh
      - ../:/workspaces/app
    command: /bin/sh -c "while sleep infinity; do :; done"
