name: publish a testing to npm

on:
  push:
    branches:
      - feature/test-docker-buildx

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}
  PLATFORMS: linux/arm64,linux/amd64
  NODE_VERSION: 18
  ALPINE_VERSION: 3
  VERSION: 0.0.1-alpha.1

jobs:
  publish-docker:
    name: Publish a testing to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Publish to docker hub - node
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            NODE_VERSION=${{ env.NODE_VERSION }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Publish to docker hub - alpine
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile.alpine
          platforms: ${{ env.PLATFORMS }}
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
            NODE_VERSION=${{ env.NODE_VERSION }}
            ALPINE_VERSION=${{ env.ALPINE_VERSION }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}-alpine, ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
